language: php

php:
  - 7.3

services: mysql

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest

before_script:
  - cp .env.travis .env
  - mysql -e 'create database blue_canary_tests;'
  - php artisan key:generate
  - php artisan migrate --seed

branches:
  only:
    - master

script:
  - composer test
