language: php

php:
  - 7.3

install:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest

before_script:
  - cp .env-example .env
  - mysql -e 'create database bc_test;'
  - php artisan key:generate
  - php artisan migrate --seed

branches:
  only:
    - master
